alias gst "git status"
alias ga "git add"
alias gaa "git add -A"
alias gau "git add -u"
alias gb "git branch"
alias gco "git checkout"
alias gsw "git switch"
alias gre "git restore"
alias glg "git log --stat"
alias glgg "git log --graph"
alias glog "git log --oneline --decorate --graph"
alias gcmsg "git commit -m"
alias gp "git push"
alias gl "git pull --prune"
alias gf "git fetch"
alias gfa "git fetch --all --prune"
alias gpsup "git push -u origin (git_current_branch)"
alias gd "git diff"

